---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [23, 24, 25]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.18'
      - env:
          ERL_FLAGS: "-enable-feature all"
        run: rebar3 test
      - env:
          ERL_FLAGS: "-enable-feature all"
        run: rebar3 escriptize && ./_build/default/bin/rebar3_lint
