---
name: build
on: [push, pull_request]
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp_vsn: ['24', '25', '26']
        rebar3_vsn: ['3.22']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
      - name: Format check
        run: rebar3 format --verify
      - env:
          ERL_FLAGS: "-enable-feature all"
        run: rebar3 test
      - env:
          ERL_FLAGS: "-enable-feature all"
        run: rebar3 escriptize && ./_build/default/bin/rebar3_lint
